"""empty message

Revision ID: ee683b883a76
Revises: 
Create Date: 2020-08-20 18:43:47.703459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee683b883a76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('n_points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.Enum('Friendly', 'Random', name='match_type'), nullable=True),
    sa.Column('white_player', sa.String(), nullable=True),
    sa.Column('black_player', sa.String(), nullable=True),
    sa.Column('winner', sa.String(), nullable=True),
    sa.Column('n_moves_white', sa.Integer(), nullable=True),
    sa.Column('n_moves_black', sa.Integer(), nullable=True),
    sa.Column('n_points_white', sa.Integer(), nullable=True),
    sa.Column('n_points_black', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['black_player'], ['players.username'], ),
    sa.ForeignKeyConstraint(['white_player'], ['players.username'], ),
    sa.ForeignKeyConstraint(['winner'], ['players.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('players')
    # ### end Alembic commands ###
