"""empty message

Revision ID: f1ae6d06ae2a
Revises: 
Create Date: 2020-08-05 09:38:19.195070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ae6d06ae2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.Enum('Friendly', 'Random', name='match_type'), nullable=True),
    sa.Column('white_player', sa.String(), nullable=True),
    sa.Column('black_player', sa.String(), nullable=True),
    sa.Column('winner', sa.String(), nullable=True),
    sa.Column('n_moves_white', sa.Integer(), nullable=True),
    sa.Column('n_moves_black', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    # ### end Alembic commands ###
